### PR TITLE
Updated copyright year

### PR DESCRIPTION
**Pull request by m0k1**

### CODE REVIEW

**Comment by Zeex** [comment]
Thanks.

**Comment by Zeex** [comment]
Ha! I just realized the previous year update was also by you. Are you seriously using this for scripting?

**Comment by m0k1** [comment]
Yea, im using it while i travel on my Ubuntu ... It's mutch better than Pawno ... :) And yea, i was updated last year too ! :dancer:

**Comment by Y-Less** [comment]
I would point out that if nothing in the code has changed, then you don't actually need to update the copyright year - even if it is in the past it is still accurate as copyright lasts for stupid numbers of years after you die.  It is basically "this was written in 2013, but the copyright still applies after that".  You could argue that changing the year is making a change worthy of new copyright, but it doesn't need it.

**Comment by eXeGOODER** [comment]
Once all the talking, then maybe qawno will update and will release?

**Pull request merged**
